name: Le Pays Réel
description: Site éducatif de réinformation politique et sociale

source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
gems:        []
timezone:    nil
encoding:    utf-8

future:      true
show_drafts: nil
limit_posts: 0
highlighter: pygments

permalink:     date
paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        true
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://lepaysreel.info
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    /images/latex
  png_url:    /images/latex
